function H = plotCylinder(x,y,z,alpha,beta,gamma,radius,len,color,isClosed,isEdge)
% Points on cylinder centered around COM
[X,Y,Z] = cyl(radius,100);
Z = (Z-0.5)*len;

% Plotting
H = hgtransform;

surf(...
      'XData', X, ...
      'YData', Y, ...
      'ZData', Z, ...
      'EdgeColor', 'none', ...
      'LineWidth', 1,      ...
      'FaceColor', color, ...
      'FaceAlpha', 1,'parent',H);

if isClosed % Adding lids
    patch(...
          'XData', X(1,:), ...
          'YData', Y(1,:), ...
          'ZData', Z(1,:), ...
          'EdgeColor', 'none',...
          'FaceColor', color,'parent',H);
    
    patch(...
          'XData', X(2,:), ...
          'YData', Y(2,:), ...
          'ZData', Z(2,:), ...
          'EdgeColor', 'none',...
          'FaceColor', color,'parent',H);
else % Coloring the inside a slightly different color
    surf(...
      'XData', 0.999*X, ...
      'YData', 0.999*Y, ...
      'ZData', Z, ...
      'EdgeColor', 'none', ...
      'LineWidth', 1,      ...
      'FaceColor', 0.8*color, ...
      'FaceAlpha', 1,'parent',H);
end


if isEdge
    plot3(X(1,:),Y(1,:),Z(1,:),'color','k','LineWidth', 1.5,'parent',H);
    plot3(X(2,:),Y(2,:),Z(2,:),'color','k','LineWidth', 1.5,'parent',H);
end

% Rotation & Translation
updatePositionOfObject(H,x,y,z,alpha,beta,gamma);
