function H = plotMagnetArtistic(x,y,z,alpha,beta,gamma,params)
% Colors
gray = [0.5,0.5,0.5];

% Plot permanent magnets
H = plotCylinder( ...
    x,y,z,alpha,beta,gamma, ...
    params.magnet.r, ...
    params.magnet.l, ...
    gray,1,1);
