function H = plotBaseArtistic(params)
H = gobjects(0);

% Colors
gray = [0.5,0.5,0.5];
copper = [0.72,0.45,0.2];
black = [0,0,0];

% Plot permanent magnets
for i = 1:length(params.permanent.r)
    Htemp = plotCylinder( ...
        params.permanent.x(i), ...
        params.permanent.y(i), ...
        params.permanent.z(i), ...
        0,0,0, ...
        params.permanent.r(i), ...
        params.permanent.l(i), ...
        gray,1,1);

    H = [H,Htemp];
end

% Plot solenoids
for i = 1:length(params.solenoids.r)
    % Computing number of windings in axial and radial directions of solenoids
    ratio = sqrt(params.solenoids.nw/(params.solenoids.l(i)*params.solenoids.r(i)));
    nwAxial  = floor(params.solenoids.l(i)*ratio);
    nwRadial = round(params.solenoids.nw/nwAxial);

    Htemp = plotWireFrame( ...
        params.solenoids.x(i), ...
        params.solenoids.y(i), ...
        params.solenoids.z(i), ...
        0,0,0, ...
        params.solenoids.r(i), ...
        params.solenoids.l(i), ...
        ceil(nwAxial/4), ...
        ceil(nwRadial/4), ...
        (0.7*copper + 0.3*black),0,0,1);
    
    H = [H,Htemp];

    Htemp = plotCylinder( ...
        params.solenoids.x(i), ...
        params.solenoids.y(i), ...
        params.solenoids.z(i), ...
        0,0,0, ...
        params.solenoids.r(i), ...
        params.solenoids.l(i), ...
        copper,1,0);

    H = [H,Htemp];
end

% Define sensor size
scale = 0.2*params.solenoids.r(1);
vertices = [scale scale, 0.7*scale].*([0 0 0; 1 0 0; 1 1 0; 0 1 0; 0 0 1; 1 0 1; 1 1 1; 0 1 1]-[0.5 0.5 0]);
faces = [1 2 3 4; 5 6 7 8; 1 2 6 5; 2 3 7 6; 3 4 8 7; 4 1 5 8];

% Plot sensors
for i = 1:length(params.sensors.x)
    patch('Vertices', vertices + [params.sensors.x(i), params.sensors.y(i), params.sensors.z(i)], 'Faces', faces, 'FaceColor', 0.5*black+0.5*gray);
end
